version: '3.8'

services:

    frontend:
      build: ../../material-applications/example-frontend/
      ports:
        - 5000:5000
      container_name: frontend

    backend:
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=postgresql
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_DATABASE
      build: ../../material-applications/example-backend/
      ports:
        - 8080:8080
      container_name: backend

    postgres:
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
        PGDATA: /database
      volumes:
        - ./database:/database
      container_name: postgresql

    redis:
      image: redis:latest
      container_name: redis

    nginx:
      image: nginx:latest
      container_name: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80

volumes:
  database: