# Use curl optimized image
FROM alpine/curl:3.14

# Use /usr/src/app as our workdir. The following instructions will be executed in this location.
WORKDIR /usr/src/app

# Copy the website.sh file
COPY website.sh .

RUN adduser -D appuser

USER appuser

# Run the script
CMD ./website.sh