version: '3.8'

services:

    frontend:
      build: ../../material-applications/example-frontend/
      ports:
        - 5000:5000
      container_name: frontend

    backend:
      environment:
        - REDIS_HOST=redis
      build: ../../material-applications/example-backend/
      ports:
        - 8080:8080
      container_name: backend

    nginx:
      image: nginx:latest
      container_name: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
      # depends_on:
      #   - frontend
      #   - backend