version: '3.8'

services:

    frontend:
      build: ../../material-applications/example-frontend/
      ports:
        - 5000:5000
      container_name: frontend

    backend:
      environment:
        - POSTGRES_HOST=postgresql
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_DATABASE
      build: ../../material-applications/example-backend/
      ports:
        - 8080:8080
      container_name: backend

    db:
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
      container_name: postgresql