FROM node:16

EXPOSE 5000

WORKDIR /usr/src/app

COPY . .

ENV REACT_APP_BACKEND_URL="http://127.0.0.1:8080"

RUN useradd -m appuser
RUN npm install && \
    npm run build && \
    npm install -g serve

USER appuser

CMD serve -s -l 5000 build
